package info.kwarc.probgen

import info.kwarc.probgen.Formula.Not

enum Formula():
  case Var(name: String)
  case Not(f: Formula)
  case And(left: Formula, right: Formula)
  case Or(left: Formula, right: Formula)
  case Implies(left: Formula, right: Formula)

trait PropLogic {

  val formula: Formula

  def apply(formula: Formula): Form =
    formula match {
      case Formula.Var(n)        => BVar(n)
      case Formula.Not(f)        => Conn(Neg, List(apply(f)))
      case Formula.And(l, r)     => Conn(And, List(apply(l), apply(r)))
      case Formula.Or(l, r)      => Conn(Or, List(apply(l), apply(r)))
      case Formula.Implies(l, r) => Conn(Implies, List(apply(l), apply(r)))
    }

}

object PropLogic {
  // we know that
  def findassignment(
      form: Form,
      satisfying: Boolean
  ): Option[Context] =
    val collected = collectVars(form)
    efficientAssignment(collected.size)
      .find(xs => {
        val sq = xs.toList
        val zipped = collected.toList.zip(sq)
        val ctx = Context(zipped)
        val eval = Evaluator(form)(using ctx)
        if satisfying then eval
        else !eval
      })
      .map(f => {
        val x = collected.toList.zip(f.toList)
        Context(x)
      })

  def findAllassignments(form: Form, satisfying: Boolean): Seq[Context] =
    val collected = collectVars(form)
    efficientAssignment(collected.size)
      .filter(xs => {
        val sq = xs.toList
        val zipped = collected.toList.zip(sq)
        val ctx = Context(zipped)
        val eval = Evaluator(form)(using ctx)
        if satisfying then eval
        else !eval
      })
      .map(f => {
        val x = collected.toList.zip(f.toList)
        Context(x)
      })

  // This is generated by chatgpt
  def assignments(n: Int): LazyList[List[Boolean]] =
    if n == 0 then LazyList(List.empty)
    else
      for
        rest <- assignments(n - 1)
        bit <- LazyList(false, true)
      yield bit :: rest

  // this also generated by chatgpt
  def efficientAssignment(n: Int): LazyList[Array[Boolean]] =
    LazyList.from(0).take(1 << n).map { mask =>
      Array.tabulate(n)(i => (mask & (1 << i)) != 0)
    }

  // This converts from and form to cnf
  def convertCNF(form: Form): Option[Form] =
    form match
      case Conn(Implies, args) => {
        // the first condition is that the list is has atleast 2 elements
        args match
          case xy :+ x => {
            if xy.isEmpty then convertCNF(x)
            else
              val first = convertCNF(Conn(Neg, List(Conn(Implies, xy)))).get
              val second = convertCNF(x).get
              Some(Conn(Or, List(first, second)))
          }
          case Nil => None
      }
      case Conn(And, args) => {
        val x = args.map(convertCNF).map(f => f.get)
        Some(Conn(And, x))
      }
      case Conn(Or, args) => {
        val x = args.map(convertCNF).map(f => f.get)
        Some(Conn(Or, x))
      }
      case Conn(Neg, args) => {
        val x = args.map(convertCNF).map(f => f.get)
        Some(Conn(Neg, x))
      }
      case BVar(name) => Some(BVar(name))
      case _          => None

  def toNNF(form: Form): Form =
    form match
      case Conn(Neg, args) => {
        Conn(Neg, args)
      }
      case a => a

  def collectVars(form: Form): Set[String] =
    var collector: Set[String] = Set()
    form match
      case BVar(n) => {
        collector = collector + n
      }
      case Conn(_, sq) => {
        val x = sq.flatMap(collectVars)
        collector = collector ++ x
      }
      case _ => {}
    collector

  def parseForm(input: String): Form =
    FormulaParser.parse(input)

}

object FormulaParser {

  def parse(input: String): Form =
    val tokens = tokenize(input)
    val parser = new Parser(tokens)
    val result = parser.parseFormula()
    if (!parser.atEnd) then
      throw new IllegalArgumentException(s"Unexpected token : ${parser.peek}")
    result

  private def tokenize(input: String): List[String] =
    input
      .replace("(", " ( ")
      .replace(")", " ) ")
      .replace("->", " -> ")
      .trim
      .split("\\s+")
      .toList
      .filter(_.nonEmpty)
  private class Parser(tokens: List[String]) {
    private var position = 0

    def atEnd: Boolean =
      position >= tokens.length

    def peek: String =
      if (atEnd) "<EOF>" else tokens(position)

    private def consume(): String =
      val token = peek
      position += 1
      token

    private def expect(token: String): Unit =
      if (peek != token)
        throw new IllegalArgumentException(s"Expected '$token' , found '$peek'")
      consume()

    def parseFormula(): Form =
      parseImplies()

    private def parseImplies(): Form =
      var left = parseOr()

      if (peek == "->" || peek == "implies") then
        consume()
        val right = parseImplies()
        Conn(Implies, List(left, right))
      else left

    private def parseOr(): Form =
      val first = parseAnd()
      if (peek != "or") then first
      else
        val forms = scala.collection.mutable.ListBuffer(first)
        while (peek == "or")
          consume()
          forms += parseAnd()
        Conn(Or, forms.toList)

    private def parseAnd(): Form =
      var left = parseNeg()
      if (peek != "and") then left
      else
        val forms = scala.collection.mutable.ListBuffer(left)
        while (peek == "and") do
          consume()
          forms += parseNeg()
        Conn(And, forms.toList)

    private def parseNeg(): Form =
      if (peek == "neg") then
        consume()
        Conn(Neg, List(parseNeg()))
      else parseAtom()

    private def parseAtom(): Form =
      if (peek == "(") then
        consume()
        val formula = parseFormula()
        expect(")")
        formula
      else if (peek.matches("[A-Za-z][A-Za-z0-9_]*")) then BVar(consume())
      else
        throw new IllegalArgumentException(
          s"Expected Variable or '(', found '$peek' "
        )

  }
}

object Mytest {

  def main(args: Array[String]) =
    val k = PropLogic.parseForm("p -> q -> p")
    println(k.toText)
    val gk = PropLogic.parseForm("(p -> q) -> p")
    println(gk.toText)
    val ans = PropLogic.findAllassignments(k, true)
    val ans2 = PropLogic.findAllassignments(gk, true)
    ans.foreach(println)
    println("=======================")
    ans2.foreach(println)

}
