package info.kwarc.probgen

import info.kwarc.probgen.Formula.Not

enum Formula():
  case Var(name: String)
  case Not(f: Formula)
  case And(left: Formula, right: Formula)
  case Or(left: Formula, right: Formula)
  case Implies(left: Formula, right: Formula)

trait PropLogic {

  val formula: Formula

  def apply(formula: Formula): Form =
    formula match {
      case Formula.Var(n)        => BVar(n)
      case Formula.Not(f)        => Conn(Neg, List(apply(f)))
      case Formula.And(l, r)     => Conn(And, List(apply(l), apply(r)))
      case Formula.Or(l, r)      => Conn(Or, List(apply(l), apply(r)))
      case Formula.Implies(l, r) => Conn(Implies, List(apply(l), apply(r)))
    }

}

object PropLogic {
  // we know that
  def findassignment(
      form: Form,
      satisfying: Boolean
  ): Option[Context] =
    val collected = collectVars(form)
    efficientAssignment(collected.size)
      .find(xs => {
        val sq = xs.toList
        val zipped = collected.toList.zip(sq)
        val ctx = Context(zipped)
        val eval = Evaluator(form)(using ctx)
        if satisfying then eval
        else !eval
      })
      .map(f => {
        val x = collected.toList.zip(f.toList)
        Context(x)
      })

  def findAllassignments(form: Form, satisfying: Boolean): Seq[Context] =
    val collected = collectVars(form)
    efficientAssignment(collected.size)
      .filter(xs => {
        val sq = xs.toList
        val zipped = collected.toList.zip(sq)
        val ctx = Context(zipped)
        val eval = Evaluator(form)(using ctx)
        if satisfying then eval
        else !eval
      })
      .map(f => {
        val x = collected.toList.zip(f.toList)
        Context(x)
      })

  // Two formulas are (semantically) equivalent iff they agree on every truth
  // assignment over the union of the variables occurring in either of them.
  def isEquivalent(f1: Form, f2: Form): Boolean =
    val vars = (collectVars(f1) ++ collectVars(f2)).toList
    efficientAssignment(vars.size).forall(xs => {
      val ctx = Context(vars.zip(xs.toList))
      Evaluator(f1)(using ctx) == Evaluator(f2)(using ctx)
    })

  // This is generated by chatgpt
  def assignments(n: Int): LazyList[List[Boolean]] =
    if n == 0 then LazyList(List.empty)
    else
      for
        rest <- assignments(n - 1)
        bit <- LazyList(false, true)
      yield bit :: rest

  // this also generated by chatgpt
  def efficientAssignment(n: Int): LazyList[Array[Boolean]] =
    LazyList.from(0).take(1 << n).map { mask =>
      Array.tabulate(n)(i => (mask & (1 << i)) != 0)
    }

  // Eliminate implications everywhere in the formula (not just at the top).
  // A right-associative chain p1 -> p2 -> ... -> pn is equivalent to
  // not(p1) or not(p2) or ... or not(p_{n-1}) or pn, so this also covers
  // Implies nodes built with more than two arguments.
  def eliminateImplies(form: Form): Form =
    form match
      case Conn(Implies, args) =>
        val elimArgs = args.map(eliminateImplies)
        val negatedPrefix = elimArgs.init.map(a => Conn(Neg, List(a)))
        Conn(Or, negatedPrefix :+ elimArgs.last)
      case Conn(op, args) => Conn(op, args.map(eliminateImplies))
      case x              => x

  // Push negations down to the literals (De Morgan's laws + double negation
  // elimination), producing Negation Normal Form. `negate` tracks whether we
  // are currently under an odd number of negations.
  def toNNF(form: Form, negate: Boolean = false): Form =
    form match
      case Conn(Neg, Seq(f)) => toNNF(f, !negate)
      case Conn(And, args)    =>
        val newArgs = args.map(a => toNNF(a, negate))
        if negate then Conn(Or, newArgs) else Conn(And, newArgs)
      case Conn(Or, args) =>
        val newArgs = args.map(a => toNNF(a, negate))
        if negate then Conn(And, newArgs) else Conn(Or, newArgs)
      case Conn(Implies, _) => toNNF(eliminateImplies(form), negate)
      case literal          => if negate then Conn(Neg, List(literal)) else literal

  // Distribute Or over And: (a and b) or c == (a or c) and (b or c).
  private def distribute(f1: Form, f2: Form): Form =
    (f1, f2) match
      case (Conn(And, args), _) => Conn(And, args.map(a => distribute(a, f2)))
      case (_, Conn(And, args)) => Conn(And, args.map(a => distribute(f1, a)))
      case _                    => Conn(Or, List(f1, f2))

  private def distributeOrOverAnd(form: Form): Form =
    form match
      case Conn(Or, args)  => args.map(distributeOrOverAnd).reduceLeft(distribute)
      case Conn(And, args) => Conn(And, args.map(distributeOrOverAnd))
      case x                => x

  // Merge nested And/Or of the same connective into one flat list, so the
  // result reads as an actual flat conjunction of disjunctions.
  private def flatten(form: Form): Form =
    form match
      case Conn(op @ (And | Or), args) =>
        val flatArgs = args.map(flatten).flatMap {
          case Conn(`op`, inner) => inner
          case f                 => List(f)
        }
        Conn(op, flatArgs)
      case Conn(op, args) => Conn(op, args.map(flatten))
      case x              => x

  // Convert an arbitrary propositional formula into Conjunctive Normal Form:
  // a flat conjunction of disjunctions of (possibly negated) variables.
  def toCNF(form: Form): Form =
    flatten(distributeOrOverAnd(toNNF(form)))

  def collectVars(form: Form): Set[String] =
    var collector: Set[String] = Set()
    form match
      case BVar(n) => {
        collector = collector + n
      }
      case Conn(_, sq) => {
        val x = sq.flatMap(collectVars)
        collector = collector ++ x
      }
      case _ => {}
    collector

  def parseForm(input: String): Form =
    FormulaParser.parse(input)

}

object FormulaParser {

  def parse(input: String): Form =
    val tokens = tokenize(input)
    val parser = new Parser(tokens)
    val result = parser.parseFormula()
    if (!parser.atEnd) then
      throw new IllegalArgumentException(s"Unexpected token : ${parser.peek}")
    result

  private def tokenize(input: String): List[String] =
    input
      .replace("(", " ( ")
      .replace(")", " ) ")
      .replace("->", " -> ")
      .trim
      .split("\\s+")
      .toList
      .filter(_.nonEmpty)
  private class Parser(tokens: List[String]) {
    private var position = 0

    def atEnd: Boolean =
      position >= tokens.length

    def peek: String =
      if (atEnd) "<EOF>" else tokens(position)

    private def consume(): String =
      val token = peek
      position += 1
      token

    private def expect(token: String): Unit =
      if (peek != token)
        throw new IllegalArgumentException(s"Expected '$token' , found '$peek'")
      consume()

    def parseFormula(): Form =
      parseImplies()

    private def parseImplies(): Form =
      var left = parseOr()

      if (peek == "->" || peek == "implies") then
        consume()
        val right = parseImplies()
        Conn(Implies, List(left, right))
      else left

    private def parseOr(): Form =
      val first = parseAnd()
      if (peek != "or") then first
      else
        val forms = scala.collection.mutable.ListBuffer(first)
        while (peek == "or")
          consume()
          forms += parseAnd()
        Conn(Or, forms.toList)

    private def parseAnd(): Form =
      var left = parseNeg()
      if (peek != "and") then left
      else
        val forms = scala.collection.mutable.ListBuffer(left)
        while (peek == "and") do
          consume()
          forms += parseNeg()
        Conn(And, forms.toList)

    private def parseNeg(): Form =
      if (peek == "neg") then
        consume()
        Conn(Neg, List(parseNeg()))
      else parseAtom()

    private def parseAtom(): Form =
      if (peek == "(") then
        consume()
        val formula = parseFormula()
        expect(")")
        formula
      else if (peek.matches("[A-Za-z][A-Za-z0-9_]*")) then BVar(consume())
      else
        throw new IllegalArgumentException(
          s"Expected Variable or '(', found '$peek' "
        )

  }
}

object Mytest {

  def main(args: Array[String]) =
    val k = PropLogic.parseForm("p -> q -> p")
    println(k.toText)
    val gk = PropLogic.parseForm("(p -> q) -> p")
    println(gk.toText)
    val ans = PropLogic.findAllassignments(k, true)
    val ans2 = PropLogic.findAllassignments(gk, true)
    ans.foreach(println)
    println("=======================")
    ans2.foreach(println)

    println("=======================")
    val cnfSrc = PropLogic.parseForm("(p -> q) -> p")
    val cnf = PropLogic.toCNF(cnfSrc)
    println(s"${cnfSrc.toText}  ==CNF==>  ${cnf.toText}")

    println("=======================")
    val f1 = PropLogic.parseForm("p -> q")
    val f2 = PropLogic.parseForm("neg p or q")
    val f3 = PropLogic.parseForm("neg (p and neg q)")
    println(s"(p -> q) equiv (neg p or q)?          ${PropLogic.isEquivalent(f1, f2)}")
    println(s"(p -> q) equiv (neg (p and neg q))?   ${PropLogic.isEquivalent(f1, f3)}")
    println(s"(p -> q) equiv (p and q)?             ${PropLogic.isEquivalent(f1, PropLogic.parseForm("p and q"))}")

}
