package info.kwarc.probgen

object PropLogic {
  // we know that
  def findassignment(
      form: Form,
      satisfying: Boolean
  ): Option[Context] =
    val collected = collectVars(form)
    efficientAssignment(collected.size)
      .find(xs => {
        val sq = xs.toList
        val zipped = collected.toList.zip(sq)
        val ctx = Context(zipped)
        val eval = Evaluator(form)(using ctx)
        if satisfying then eval
        else !eval
      })
      .map(f => {
        val x = collected.toList.zip(f.toList)
        Context(x)
      })

  def findAllassignments(form: Form, satisfying: Boolean): Seq[Context] =
    val collected = collectVars(form)
    efficientAssignment(collected.size)
      .filter(xs => {
        val sq = xs.toList
        val zipped = collected.toList.zip(sq)
        val ctx = Context(zipped)
        val eval = Evaluator(form)(using ctx)
        if satisfying then eval
        else !eval
      })
      .map(f => {
        val x = collected.toList.zip(f.toList)
        Context(x)
      })

  // Two formulas are (semantically) equivalent iff they agree on every truth
  // assignment over the union of the variables occurring in either of them.
  def isEquivalent(f1: Form, f2: Form): Boolean =
    val vars = (collectVars(f1) ++ collectVars(f2)).toList
    efficientAssignment(vars.size).forall(xs => {
      val ctx = Context(vars.zip(xs.toList))
      Evaluator(f1)(using ctx) == Evaluator(f2)(using ctx)
    })

  // This is generated by chatgpt
  def assignments(n: Int): LazyList[List[Boolean]] =
    if n == 0 then LazyList(List.empty)
    else
      for
        rest <- assignments(n - 1)
        bit <- LazyList(false, true)
      yield bit :: rest

  // this also generated by chatgpt
  def efficientAssignment(n: Int): LazyList[Array[Boolean]] =
    LazyList.from(0).take(1 << n).map { mask =>
      Array.tabulate(n)(i => (mask & (1 << i)) != 0)
    }

  // Eliminate implications everywhere in the formula (not just at the top).
  // A right-associative chain p1 -> p2 -> ... -> pn is equivalent to
  // not(p1) or not(p2) or ... or not(p_{n-1}) or pn, so this also covers
  // Implies nodes built with more than two arguments.
  def eliminateImplies(form: Form): Form =
    form match
      case Conn(Implies, args) =>
        val elimArgs = args.map(eliminateImplies)
        val negatedPrefix = elimArgs.init.map(a => Conn(Neg, List(a)))
        Conn(Or, negatedPrefix :+ elimArgs.last)
      case Conn(op, args) => Conn(op, args.map(eliminateImplies))
      case x              => x

  // Push negations down to the literals (De Morgan's laws + double negation
  // elimination), producing Negation Normal Form. `negate` tracks whether we
  // are currently under an odd number of negations.
  def toNNF(form: Form, negate: Boolean = false): Form =
    form match
      case Conn(Neg, Seq(f)) => toNNF(f, !negate)
      case Conn(And, args)    =>
        val newArgs = args.map(a => toNNF(a, negate))
        if negate then Conn(Or, newArgs) else Conn(And, newArgs)
      case Conn(Or, args) =>
        val newArgs = args.map(a => toNNF(a, negate))
        if negate then Conn(And, newArgs) else Conn(Or, newArgs)
      case Conn(Implies, _) => toNNF(eliminateImplies(form), negate)
      case literal          => if negate then Conn(Neg, List(literal)) else literal

  // Distribute Or over And: (a and b) or c == (a or c) and (b or c).
  private def distributeOr(f1: Form, f2: Form): Form =
    (f1, f2) match
      case (Conn(And, args), _) => Conn(And, args.map(a => distributeOr(a, f2)))
      case (_, Conn(And, args)) => Conn(And, args.map(a => distributeOr(f1, a)))
      case _                    => Conn(Or, List(f1, f2))

  private def distributeOrOverAnd(form: Form): Form =
    form match
      case Conn(Or, args)  => args.map(distributeOrOverAnd).reduceLeft(distributeOr)
      case Conn(And, args) => Conn(And, args.map(distributeOrOverAnd))
      case x                => x

  // Distribute And over Or: (a or b) and c == (a and c) or (b and c).
  private def distributeAnd(f1: Form, f2: Form): Form =
    (f1, f2) match
      case (Conn(Or, args), _) => Conn(Or, args.map(a => distributeAnd(a, f2)))
      case (_, Conn(Or, args)) => Conn(Or, args.map(a => distributeAnd(f1, a)))
      case _                   => Conn(And, List(f1, f2))

  private def distributeAndOverOr(form: Form): Form =
    form match
      case Conn(And, args) => args.map(distributeAndOverOr).reduceLeft(distributeAnd)
      case Conn(Or, args)  => Conn(Or, args.map(distributeAndOverOr))
      case x                => x

  // Merge nested And/Or of the same connective into one flat list, so the
  // result reads as an actual flat conjunction of disjunctions.
  private def flatten(form: Form): Form =
    form match
      case Conn(op @ (And | Or), args) =>
        val flatArgs = args.map(flatten).flatMap {
          case Conn(`op`, inner) => inner
          case f                 => List(f)
        }
        Conn(op, flatArgs)
      case Conn(op, args) => Conn(op, args.map(flatten))
      case x              => x

  // Convert an arbitrary propositional formula into Conjunctive Normal Form:
  // a flat conjunction of disjunctions of (possibly negated) variables.
  def toCNF(form: Form): Form =
    flatten(distributeOrOverAnd(toNNF(form)))

  private def isLiteral(f: Form): Boolean =
    f match
      case BVar(_)              => true
      case Conn(Neg, Seq(BVar(_))) => true
      case _                     => false

  // Is this formula literally (syntactically) in Conjunctive Normal Form,
  // i.e. a conjunction of disjunctions of literals? Used to grade CNF
  // exercises structurally, on top of just checking equivalence.
  def isCNF(form: Form): Boolean =
    def isClause(f: Form): Boolean = f match
      case Conn(Or, lits) => lits.forall(isLiteral)
      case l              => isLiteral(l)
    form match
      case Conn(And, clauses) => clauses.forall(isClause)
      case f                  => isClause(f)

  // Is this formula literally (syntactically) in Disjunctive Normal Form,
  // i.e. a disjunction of conjunctions of literals? Dual of isCNF.
  def isDNF(form: Form): Boolean =
    def isTerm(f: Form): Boolean = f match
      case Conn(And, lits) => lits.forall(isLiteral)
      case l                => isLiteral(l)
    form match
      case Conn(Or, terms) => terms.forall(isTerm)
      case f                => isTerm(f)

  // Convert an arbitrary propositional formula into Disjunctive Normal Form:
  // a flat disjunction of conjunctions of (possibly negated) variables.
  // Dual of toCNF: same NNF step, then distribute And over Or instead.
  def toDNF(form: Form): Form =
    flatten(distributeAndOverOr(toNNF(form)))

  // ── Tseitin transformation ─────────────────────────────────────────────
  // toCNF/toDNF above distribute connectives out, which can blow the formula
  // up exponentially (e.g. a balanced tree of n Ors nested under Ands).
  // Tseitin's transformation avoids that: it introduces one fresh variable
  // per subformula and adds small "definitional" clauses saying that
  // variable is equivalent to the subformula it names, giving a result whose
  // size is linear in the size of the input (at the cost of extra variables,
  // and of being only *equisatisfiable* with the input rather than
  // equivalent to it).

  private def freshVarSupply(taken: Set[String]): () => String =
    var counter = 0
    () =>
      var name = s"t$counter"
      counter += 1
      while taken.contains(name) do
        name = s"t$counter"
        counter += 1
      name

  private def neg(f: Form): Form = Conn(Neg, List(f))
  private def clause(lits: Form*): Form = Conn(Or, lits.toList)

  // Walks the formula bottom-up, replacing every And/Or/Neg/Implies node by a
  // fresh literal `p` and recording the CNF clauses that pin `p` down to be
  // equivalent to that node (in terms of the literals its children were
  // already replaced by). Returns the literal for the whole formula together
  // with every clause collected along the way.
  private def tseitinEncode(
      form: Form,
      fresh: () => String
  ): (Form, List[Form]) =
    form match
      case BVar(_) | Pred(_, _) => (form, Nil)
      case Conn(Implies, _)     => tseitinEncode(eliminateImplies(form), fresh)
      case Conn(Neg, Seq(a)) =>
        val (la, defsA) = tseitinEncode(a, fresh)
        val p = BVar(fresh())
        // p <-> not(la) :  (not(p) or not(la)) and (p or la)
        val defs = List(clause(neg(p), neg(la)), clause(p, la))
        (p, defsA ++ defs)
      case Conn(And, args) =>
        val encoded = args.map(tseitinEncode(_, fresh))
        val lits = encoded.map(_._1)
        val p = BVar(fresh())
        // p <-> (l1 and ... and ln):
        //   forward:  for each li, (not(p) or li)
        //   backward: (p or not(l1) or ... or not(ln))
        val forward = lits.map(l => clause(neg(p), l)).toList
        val backward = clause(p +: lits.map(neg)*)
        (p, encoded.flatMap(_._2).toList ++ forward :+ backward)
      case Conn(Or, args) =>
        val encoded = args.map(tseitinEncode(_, fresh))
        val lits = encoded.map(_._1)
        val p = BVar(fresh())
        // p <-> (l1 or ... or ln):
        //   forward:  (not(p) or l1 or ... or ln)
        //   backward: for each li, (p or not(li))
        val forward = clause(neg(p) +: lits*)
        val backward = lits.map(l => clause(p, neg(l))).toList
        (p, encoded.flatMap(_._2).toList ++ (forward :: backward))
      case atom => (atom, Nil)

  // Tseitin CNF: equisatisfiable with `form`, linear in its size. The result
  // is (root-literal and def-clause and def-clause and ...); asserting it
  // forces the fresh root literal true, which forces `form` itself true.
  def tseitinCNF(form: Form): Form =
    val fresh = freshVarSupply(collectVars(form))
    val (rootLit, defs) = tseitinEncode(form, fresh)
    flatten(Conn(And, rootLit :: defs))

  // Tseitin DNF: negating a flat CNF into a flat DNF is free (De Morgan on a
  // two-level formula needs no redistribution), so build it as
  // not(tseitinCNF(not(form))). This is linear in size and, mirroring how
  // tseitinCNF preserves satisfiability of `form`, preserves validity of
  // `form`: `form` is a tautology iff the returned DNF is.
  def tseitinDNF(form: Form): Form =
    flatten(toNNF(neg(tseitinCNF(neg(form)))))

  def collectVars(form: Form): Set[String] =
    var collector: Set[String] = Set()
    form match
      case BVar(n) => {
        collector = collector + n
      }
      case Conn(_, sq) => {
        val x = sq.flatMap(collectVars)
        collector = collector ++ x
      }
      case _ => {}
    collector

  def parseForm(input: String): Form =
    FormulaParser.parse(input)

}

object FormulaParser {

  def parse(input: String): Form =
    val tokens = tokenize(input)
    val parser = new Parser(tokens)
    val result = parser.parseFormula()
    if (!parser.atEnd) then
      throw new IllegalArgumentException(s"Unexpected token : ${parser.peek}")
    result

  private def tokenize(input: String): List[String] =
    input
      .replace("(", " ( ")
      .replace(")", " ) ")
      .replace("->", " -> ")
      .trim
      .split("\\s+")
      .toList
      .filter(_.nonEmpty)
  private class Parser(tokens: List[String]) {
    private var position = 0

    def atEnd: Boolean =
      position >= tokens.length

    def peek: String =
      if (atEnd) "<EOF>" else tokens(position)

    private def consume(): String =
      val token = peek
      position += 1
      token

    private def expect(token: String): Unit =
      if (peek != token)
        throw new IllegalArgumentException(s"Expected '$token' , found '$peek'")
      consume()

    def parseFormula(): Form =
      parseImplies()

    private def parseImplies(): Form =
      var left = parseOr()

      if (peek == "->" || peek == "implies") then
        consume()
        val right = parseImplies()
        Conn(Implies, List(left, right))
      else left

    private def parseOr(): Form =
      val first = parseAnd()
      if (peek != "or") then first
      else
        val forms = scala.collection.mutable.ListBuffer(first)
        while (peek == "or")
          consume()
          forms += parseAnd()
        Conn(Or, forms.toList)

    private def parseAnd(): Form =
      var left = parseNeg()
      if (peek != "and") then left
      else
        val forms = scala.collection.mutable.ListBuffer(left)
        while (peek == "and") do
          consume()
          forms += parseNeg()
        Conn(And, forms.toList)

    private def parseNeg(): Form =
      // accept both "neg" and "not" - Neg.text (used by Form#toText, i.e.
      // what's shown to users as e.g. a problem's solution) renders as
      // "not", so the parser must accept that spelling too or its own
      // output wouldn't parse back in
      if (peek == "neg" || peek == "not") then
        consume()
        Conn(Neg, List(parseNeg()))
      else parseAtom()

    private def parseAtom(): Form =
      if (peek == "(") then
        consume()
        val formula = parseFormula()
        expect(")")
        formula
      else if (peek.matches("[A-Za-z][A-Za-z0-9_]*")) then BVar(consume())
      else
        throw new IllegalArgumentException(
          s"Expected Variable or '(', found '$peek' "
        )

  }
}

object Mytest {

  def main(args: Array[String]) =
    val k = PropLogic.parseForm("p -> q -> p")
    println(k.toText)
    val gk = PropLogic.parseForm("(p -> q) -> p")
    println(gk.toText)
    val ans = PropLogic.findAllassignments(k, true)
    val ans2 = PropLogic.findAllassignments(gk, true)
    ans.foreach(println)
    println("=======================")
    ans2.foreach(println)

    println("=======================")
    val cnfSrc = PropLogic.parseForm("(p -> q) -> p")
    val cnf = PropLogic.toCNF(cnfSrc)
    println(s"${cnfSrc.toText}  ==CNF==>  ${cnf.toText}")

    println("=======================")
    val f1 = PropLogic.parseForm("p -> q")
    val f2 = PropLogic.parseForm("neg p or q")
    val f3 = PropLogic.parseForm("neg (p and neg q)")
    println(s"(p -> q) equiv (neg p or q)?          ${PropLogic.isEquivalent(f1, f2)}")
    println(s"(p -> q) equiv (neg (p and neg q))?   ${PropLogic.isEquivalent(f1, f3)}")
    println(s"(p -> q) equiv (p and q)?             ${PropLogic.isEquivalent(f1, PropLogic.parseForm("p and q"))}")

    println("=======================")
    val dnfSrc = PropLogic.parseForm("(p and q) or (neg r and s)")
    val dnf = PropLogic.toDNF(dnfSrc)
    println(s"${dnfSrc.toText}  ==DNF==>  ${dnf.toText}")
    println(s"still equivalent to original? ${PropLogic.isEquivalent(dnfSrc, dnf)}")

    println("=======================")
    val tCnf = PropLogic.tseitinCNF(gk)
    println(s"${gk.toText}  ==Tseitin CNF==>  ${tCnf.toText}")
    val tDnf = PropLogic.tseitinDNF(gk)
    println(s"${gk.toText}  ==Tseitin DNF==>  ${tDnf.toText}")
    println(s"gk is a tautology? ${PropLogic.findassignment(gk, false).isEmpty}")
    println(s"tseitin DNF is a tautology? ${PropLogic.findassignment(tDnf, false).isEmpty}")

    println("=======================")
    for (_ <- 1 to 5)
      val rf = PropFormulaGenerator.generate(
        vars = List("p", "q", "r"),
        minDepth = 2,
        maxDepth = 4,
        minVars = 2,
        weights = ConnectiveWeights(and = 40, or = 20, implies = 30, not = 10)
      )
      println(rf.toText)

    println("=======================")
    val problem = LogicProblemGenerator.make()
    val subs = problem.chooseSubproblems()
    subs.foreach { sub =>
      println(s"[${sub.id}] ${sub.question().toText}")
      println(s"  expected: ${sub.solution().toText}")
    }
    val cnfSub = subs.find(_.id == "cnf").get
    println(s"  submit expected solution -> ${cnfSub.checkSolution(cnfSub.solution().toText)}")
    println(s"  submit garbage 'p and'    -> ${cnfSub.checkSolution("p and")}")
    println(s"  submit 'p or not p'       -> ${cnfSub.checkSolution("p or neg p")}")

}
